site_name: 🔐 safejax
site_url: https://github.com/alvarobartt/safejax
site_author: Alvaro Bartolome
site_description: Serialize JAX, Flax, Haiku, or Objax model params with `safetensors`

repo_name: alvarobartt/safejax
repo_url: https://github.com/alvarobartt/safejax

copyright: Copyright (c) 2022-present Alvaro Bartolome <alvarobartt@yahoo.com>

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/safejax/
    - icon: fontawesome/brands/github
      link: https://github.com/alvarobartt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alvarobartt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alvarobartt/

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Usage: usage.md
  - Why safejax?: why_safejax.md
  - Examples: examples.md
  - Reference:
      - safejax.core.load: api/core_load.md
      - safejax.core.save: api/core_save.md
      - safejax.utils: api/utils.md
  - License: license.md
